-- ============================================================
--  Catalogue GAEC Causselot 2026 (bons de commande jeune bovin,
--  boeuf, plats cuisines). PLU sequentiel, EAN-13 interne calcule.
--  INSERT IGNORE : relançable, ne recree pas un produit deja present.
--  Prix repris du bon de commande (valeur basse si fourchette).
-- ============================================================

INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0001','2000010000005','Pavés de veau (noix, noix pâtissière)','Pavés de veau (noix, noix pâtissière)','Jeune bovin','viande_bovine',26.8,'barquette','froid_positif',1,10);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0002','2000020000002','Escalopes 1er choix (noix, noix pâtissière)','Escalopes 1er choix (noix, noix pâtissiè','Jeune bovin','viande_bovine',26.8,'barquette','froid_positif',1,20);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0003','2000030000009','Escalopes 2nd choix (sous-noix, rond de noix, baronne)','Escalopes 2nd choix (sous-noix, rond de ','Jeune bovin','viande_bovine',23.2,'barquette','froid_positif',1,30);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0004','2000040000006','Escalopes fines (sous-noix)','Escalopes fines (sous-noix)','Jeune bovin','viande_bovine',23.2,'barquette','froid_positif',1,40);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0005','2000050000003','Bavette aloyau - Onglet - Hampe','Bavette aloyau - Onglet - Hampe','Jeune bovin','viande_bovine',25.3,'barquette','froid_positif',1,50);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0006','2000060000000','Rôti 1er choix (noix pâtissière)','Rôti 1er choix (noix pâtissière)','Jeune bovin','viande_bovine',26.8,'barquette','froid_positif',1,60);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0007','2000070000007','Rôti 2nd choix (rond, baronne)','Rôti 2nd choix (rond, baronne)','Jeune bovin','viande_bovine',23.2,'barquette','froid_positif',1,70);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0008','2000080000004','Quasi (escalope ou rôti)','Quasi (escalope ou rôti)','Jeune bovin','viande_bovine',32,'barquette','froid_positif',1,80);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0009','2000090000001','Côte découverte avec ou sans os','Côte découverte avec ou sans os','Jeune bovin','viande_bovine',21.5,'barquette','froid_positif',1,90);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0010','2000100000007','Côte première avec ou sans os','Côte première avec ou sans os','Jeune bovin','viande_bovine',25.2,'barquette','froid_positif',1,100);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0011','2000110000004','Côte filet avec ou sans os','Côte filet avec ou sans os','Jeune bovin','viande_bovine',27.8,'barquette','froid_positif',1,110);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0012','2000120000001','Filet ou grenadin','Filet ou grenadin','Jeune bovin','viande_bovine',37,'barquette','froid_positif',1,120);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0013','2000130000008','Viande hachée assaisonnée (veau)','Viande hachée assaisonnée (veau)','Jeune bovin',NULL,19,'barquette','froid_positif',1,130);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0014','2000140000005','Chipolaveaux','Chipolaveaux','Jeune bovin',NULL,18,'barquette','froid_positif',1,140);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0015','2000150000002','Escalopes marinées','Escalopes marinées','Jeune bovin',NULL,25.3,'barquette','froid_positif',1,150);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0016','2000160000009','Sauté (collier-épaule)','Sauté (collier-épaule)','Jeune bovin','viande_bovine',13.7,'barquette','froid_positif',1,160);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0017','2000170000006','Blanquette (poitrine)','Blanquette (poitrine)','Jeune bovin','viande_bovine',15.4,'barquette','froid_positif',1,170);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0018','2000180000003','Plat de côte avec ou sans os (veau)','Plat de côte avec ou sans os (veau)','Jeune bovin','viande_bovine',9.3,'barquette','froid_positif',1,180);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0019','2000190000000','Tendrons','Tendrons','Jeune bovin','viande_bovine',15.4,'barquette','froid_positif',1,190);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0020','2000200000006','Jarret (veau)','Jarret (veau)','Jeune bovin','viande_bovine',13,'barquette','froid_positif',1,200);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0021','2000210000003','Foie (veau)','Foie (veau)','Jeune bovin',NULL,21.3,'barquette','froid_positif',1,210);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0022','2000220000000','Pavé de bœuf (tende de tranche, tranche)','Pavé de bœuf (tende de tranche, tranche)','Bœuf','viande_bovine',24.6,'barquette','froid_positif',1,220);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0023','2000230000007','Steak 1er choix (tende de tranche, tranche)','Steak 1er choix (tende de tranche, tranc','Bœuf','viande_bovine',24.6,'barquette','froid_positif',1,230);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0024','2000240000004','Steak 2nd choix (baronne, rond de gîte)','Steak 2nd choix (baronne, rond de gîte)','Bœuf','viande_bovine',20.2,'barquette','froid_positif',1,240);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0025','2000250000001','Onglet - Hampe - Bavette','Onglet - Hampe - Bavette','Bœuf','viande_bovine',25.5,'barquette','froid_positif',1,250);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0026','2000260000008','Rumsteak (pavé, steak ou rôti)','Rumsteak (pavé, steak ou rôti)','Bœuf','viande_bovine',29.3,'barquette','froid_positif',1,260);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0027','2000270000005','Rôti 1er choix (tranche)','Rôti 1er choix (tranche)','Bœuf','viande_bovine',24.6,'barquette','froid_positif',1,270);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0028','2000280000002','Rôti 2nd choix (baronne, rond de gîte)','Rôti 2nd choix (baronne, rond de gîte)','Bœuf','viande_bovine',20.2,'barquette','froid_positif',1,280);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0029','2000290000009','Filet ou tournedos','Filet ou tournedos','Bœuf','viande_bovine',36,'barquette','froid_positif',1,290);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0030','2000300000005','Basse-côte','Basse-côte','Bœuf','viande_bovine',20.4,'barquette','froid_positif',1,300);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0031','2000310000002','Faux filet','Faux filet','Bœuf','viande_bovine',31,'barquette','froid_positif',1,310);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0032','2000320000009','Côte (bœuf)','Côte (bœuf)','Bœuf','viande_bovine',29.2,'barquette','froid_positif',1,320);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0033','2000330000006','Entrecôte','Entrecôte','Bœuf','viande_bovine',30.3,'barquette','froid_positif',1,330);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0034','2000340000003','Viande hachée assaisonnée (bœuf)','Viande hachée assaisonnée (bœuf)','Bœuf',NULL,18.5,'barquette','froid_positif',1,340);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0035','2000350000000','Merguez','Merguez','Bœuf',NULL,16.9,'barquette','froid_positif',1,350);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0036','2000360000007','Bourguignon','Bourguignon','Bœuf','viande_bovine',13.7,'barquette','froid_positif',1,360);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0037','2000370000004','Plat de côte avec os','Plat de côte avec os','Bœuf','viande_bovine',8.1,'barquette','froid_positif',1,370);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0038','2000380000001','Plat de côte sans os','Plat de côte sans os','Bœuf','viande_bovine',9.7,'barquette','froid_positif',1,380);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0039','2000390000008','Morceau à braiser (jumeau, macreuse)','Morceau à braiser (jumeau, macreuse)','Bœuf','viande_bovine',15.2,'barquette','froid_positif',1,390);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0040','2000400000004','Jarret (bœuf)','Jarret (bœuf)','Bœuf','viande_bovine',11.3,'barquette','froid_positif',1,400);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0041','2000410000001','Sauté à l\'oignon','Sauté à l\'oignon','Plats cuisinés','traiteur',21.2,'barquette','froid_positif',1,410);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0042','2000420000008','Navarin','Navarin','Plats cuisinés','traiteur',20.6,'barquette','froid_positif',1,420);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0043','2000430000005','Blanquette de veau','Blanquette de veau','Plats cuisinés','traiteur',19.5,'barquette','froid_positif',1,430);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0044','2000440000002','Osso Bucco','Osso Bucco','Plats cuisinés','traiteur',21,'barquette','froid_positif',1,440);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0045','2000450000009','Tajine','Tajine','Plats cuisinés','traiteur',21.9,'barquette','froid_positif',1,450);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0046','2000460000006','Rognons à l\'armagnac','Rognons à l\'armagnac','Plats cuisinés','traiteur',13.9,'barquette','froid_positif',1,460);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0047','2000470000003','Tête de veau sauce gribiche','Tête de veau sauce gribiche','Plats cuisinés','traiteur',13.5,'barquette','froid_positif',1,470);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0048','2000480000000','Paupiettes de veau','Paupiettes de veau','Plats cuisinés','traiteur',16.9,'barquette','froid_positif',1,480);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0049','2000490000007','Tripoux (conserve)','Tripoux (conserve)','Plats cuisinés','traiteur',21.3,'barquette','froid_positif',1,490);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0050','2000500000003','Tripes (conserve)','Tripes (conserve)','Plats cuisinés','traiteur',15.1,'barquette','froid_positif',1,500);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0051','2000510000000','Bolognaise (bocal)','Bolognaise (bocal)','Plats cuisinés','traiteur',17.5,'barquette','froid_positif',1,510);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0052','2000520000007','Poitrine farcie','Poitrine farcie','Plats cuisinés','traiteur',20.4,'barquette','froid_positif',1,520);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0053','2000530000004','Farçous','Farçous','Plats cuisinés','traiteur',20.4,'barquette','froid_positif',1,530);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0054','2000540000001','Paté en croûte de veau','Paté en croûte de veau','Plats cuisinés','traiteur',25,'barquette','froid_positif',1,540);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0055','2000550000008','Rôti froid en tranches','Rôti froid en tranches','Plats cuisinés','traiteur',24,'barquette','froid_positif',1,550);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0056','2000560000005','Salade de pot au feu','Salade de pot au feu','Plats cuisinés','traiteur',17.5,'barquette','froid_positif',1,560);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0057','2000570000002','Bœuf braisé à l\'orange','Bœuf braisé à l\'orange','Plats cuisinés','traiteur',20,'barquette','froid_positif',1,570);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0058','2000580000009','Bœuf bourguignon','Bœuf bourguignon','Plats cuisinés','traiteur',20.4,'barquette','froid_positif',1,580);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0059','2000590000006','Chili con carne','Chili con carne','Plats cuisinés','traiteur',19.8,'barquette','froid_positif',1,590);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0060','2000600000002','Boulettes au basilic','Boulettes au basilic','Plats cuisinés','traiteur',22.3,'barquette','froid_positif',1,600);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0061','2000610000009','Choux farcis','Choux farcis','Plats cuisinés','traiteur',19.7,'barquette','froid_positif',1,610);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0062','2000620000006','Lasagnes','Lasagnes','Plats cuisinés','traiteur',16.2,'barquette','froid_positif',1,620);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0063','2000630000003','Hachis parmentier','Hachis parmentier','Plats cuisinés','traiteur',14,'barquette','froid_positif',1,630);
INSERT IGNORE INTO `produits` (`plu`,`ean13`,`libelle`,`libelle_court`,`famille`,`classe_traca`,`prix_kg`,`conditionnement`,`conservation`,`actif`,`ordre`) VALUES ('0064','2000640000000','Moussaka','Moussaka','Plats cuisinés','traiteur',16.7,'barquette','froid_positif',1,640);
